### ISSUE TITLE
special cases for URL formatting

### ISSUE THREAD

**Issue by Pascalco** [Wikidata/primarysources#79] opened 2016-02-26 15:50 UTC
To format snak values with a link, the URL formatter (P1630) is retrieved and $1 is replaced by the snak value. For some properties (P213, P345, P502, P628, P882, P1323) this simple approach fails because further formatting has to be done to produce valid links. The rules of the additional formatting can be looked up in https://www.wikidata.org/wiki/MediaWiki:Gadget-AuthorityControl.js

**Comment by tfmorris** [comment] 2016-02-26 15:55
This sounds like a duplicate of #78. Thanks for the link to the rules though.

**Comment by GlorianY** [comment] 2016-10-14 13:12
In order to ease us (the Wikidata dev team) to track the issues of the primary sources tool, we have created a Phabricator ticket for this issue: https://phabricator.wikimedia.org/T148170

Moving forward, please drop your comments onto that Phabricator ticket.

**Closed** 2016-11-07 15:38 UTC
Labels: front-end, open task
